networks:
  kafka-cluster:
    driver: bridge

version: '3'
services:
  lenses:
    image: lensesio/fast-data-dev:3.3
    container_name: lenses
    ports:
      - 3030:3030
      - 9092:9092
      - 2181:2181
      - 8081-8083:8081-8083
      - 9581-9585:9581-9585
    environment:
      - ADV_HOST=127.0.0.1
      - AWS_ACCESS_KEY_ID=minio
      - AWS_SECRET_ACCESS_KEY=minio123
      - S3_ENDPOINT=http://minio:9000
    networks:
      - kafka-cluster
    depends_on:
      - minio
    links:
      - minio
    volumes:
      - ./kafka-connector-conf:/kafka-connector-conf
  minio:
    image: quay.io/minio/minio:RELEASE.2023-02-22T18-23-45Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
      - MINIO_SERVER_URL=http://minio:9000
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://minio:9000/minio/health/live"
        ]
      interval: 30s
      timeout: 20s
      retries: 3
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - kafka-cluster
    volumes:
      - ./minio_data:/data
