networks:
  flink-cluster:
    driver: bridge

version: '3'
services:
  jobmanager:
    image: flink-kafka:latest
    build:
      context: .
      dockerfile: flink-kafka.Dockerfile
    ports:
      - 8081:8081
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - flink-cluster
    volumes:
      - ./src/flink_kafka_poc:/opt/src/

  taskmanager:
    image: flink-kafka:latest
    build:
      context: .
      dockerfile: flink-kafka.Dockerfile
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - flink-cluster
